import type { NextPage } from 'next';
import Head from 'next/head';
import { useState } from 'react';
import { trpc } from '../utils/trpc';
import { AddIncomeDialog } from './features/Income';
import { AddExpenseDialog } from './features/Expense';
import { GetBudgetModal } from './features/GetBudget';
import { BeakerIcon, PencilIcon } from '@heroicons/react/24/solid';
import { EditIncomeDialog } from './features/EditIncomes';
import { IncomeCard } from './features/Income/components/IncomeCard';
import { ExpenseCard } from './features/Expense/ExpenseCard/ExpenseCard';

const Home: NextPage = () => {
    const [isAddIncomeModalOpen, setIsAddIncomeModalOpen] = useState(false);
    const [isAddExpenseModalOpen, setIsAddExpenseModalOpen] = useState(false);
    const [isGetBudgetModalOpen, setIsGetBudgetModalOpen] = useState(false);
    const incomes = trpc.useQuery(['income.getAll']);
    const expenses = trpc.useQuery(['expense.getAll']);

    return (
        <>
            <Head>
                <title>Budget Fine</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className="flex items-center justify-center min-h-screen">
                <div className="flex flex-col space-y-10">
                    <button
                        onClick={() => setIsGetBudgetModalOpen(true)}
                        className="bg-blue-400 py-4 text-white hover:bg-blue-500"
                    >
                        Get Budget!
                    </button>
                    <GetBudgetModal
                        incomes={incomes?.data}
                        isOpen={isGetBudgetModalOpen}
                        setIsOpen={setIsGetBudgetModalOpen}
                    />
                    <div className="flex space-x-10">
                        <div className="flex flex-col space-y-6">
                            <h2 className="text-3xl text-center font-bold">
                                Incomes
                            </h2>
                            <button
                                onClick={() => setIsAddIncomeModalOpen(true)}
                                className="py-2 px-4 bg-green-500 hover:bg-green-600 text-white"
                            >
                                Add income
                            </button>
                            <AddIncomeDialog
                                isOpen={isAddIncomeModalOpen}
                                setIsOpen={setIsAddIncomeModalOpen}
                            />
                            {incomes?.data &&
                                incomes.data.map((income) => (
                                    <IncomeCard
                                        key={income.id}
                                        income={income}
                                    />
                                ))}
                        </div>
                        <div className="flex flex-col space-y-6">
                            <h2 className="text-3xl text-center font-bold">
                                Expenses
                            </h2>
                            <button
                                onClick={() => setIsAddExpenseModalOpen(true)}
                                className="py-2 px-4 bg-red-500 hover:bg-red-600 text-white"
                            >
                                Add expense
                            </button>
                            <AddExpenseDialog
                                isOpen={isAddExpenseModalOpen}
                                setIsOpen={setIsAddExpenseModalOpen}
                            />
                            {expenses?.data &&
                                expenses.data.map((expense) => (
                                    <ExpenseCard
                                        key={expense.id}
                                        expense={expense}
                                    />
                                ))}
                        </div>
                    </div>
                </div>
            </main>
        </>
    );
};

export default Home;
